# Generated by Django 2.2 on 2019-04-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='souscategorie',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.SousCategorie'),
        ),
    ]
