# Generated by Django 2.2 on 2019-04-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190403_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='souscategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.SousCategorie'),
        ),
    ]
