# Generated by Django 2.2 on 2019-04-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190403_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='image',
        ),
    ]
