# Generated by Django 2.2 on 2019-04-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_publication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.File'),
        ),
    ]
